name: Build and Deploy

on:
  push:
    branches: [main]      # auto-triggers on every push to main
  workflow_dispatch:      # manual trigger button in GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: tech-news-agent-agent
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:latest .
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region eu-north-1 | docker login \
              --username AWS \
              --password-stdin 853506921311.dkr.ecr.eu-north-1.amazonaws.com
            cd ~/tech-news-agent
            docker compose down 
            docker compose pull
            docker compose up -d